version: '3.8'

services:
  sonarqube:
    image: sonarqube:community
    container_name: fusion-sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - sonarnet

  sonarqube-db:
    image: postgres:15
    container_name: fusion-sonarqube-db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - sonarnet

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: fusion-sonar-scanner
    depends_on:
      - sonarqube
    environment:
      SONAR_HOST_URL: http://sonarqube:9000
      SONAR_LOGIN: ${SONAR_TOKEN:-admin}
    volumes:
      - ./:/usr/src
    networks:
      - sonarnet
    command: 
      - "-Dsonar.projectKey=fusion-electronics-ecommerce"
      - "-Dsonar.sources=."
      - "-Dsonar.host.url=http://sonarqube:9000"

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:

networks:
  sonarnet:
    driver: bridge
